### ISSUE TITLE
🛠 Tooling: Allcontributors bot isn't running

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SquiggleTools/boston-ts-website#300]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/boston-ts-website/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/SquiggleTools/boston-ts-website?tab=readme-ov-file#contributors should have a whole list of contributors, as informed by comments such as https://github.com/SquiggleTools/boston-ts-website/pull/298#issuecomment-2254613607... but it isn't! What's going on?

### Additional Info

I'm betting it's probably an app installation issue from when I switched the repo's parent organization. I'll look into it.

FYI @astorije 

💖

**Comment by astorije** [comment]
> I'm betting it's probably an app installation issue from when I switched the repo's parent organization.

Any chance the Renovate bot showing us a total lack of interest could have the same issue?

**Comment by JoshuaKGoldberg** [comment]
Aha! That's it! I just installed the app and it should be running now.
